### ISSUE TITLE
Not support solr data on HDFS?

### ISSUE THREAD

**Issue by csxuyang** [abajwa-hw/solr-stack#6]
when I set solr_datadir on  hdfs ,it can not start successfully.

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/SOLR/package/scripts/master.py", line 164, in <module>
    Master().execute()
  File "/usr/lib/python2.6/site-packages/resource_management/libraries/script/script.py", line 219, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/SOLR/package/scripts/master.py", line 104, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/HDP/2.4/services/SOLR/package/scripts/master.py", line 86, in configure
    File(format("{solr_datadir}/solr.xml"), content=xml_content, owner=params.solr_user)  
  File "/usr/lib/python2.6/site-packages/resource_management/core/base.py", line 154, in **init**
    self.env.run()
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 158, in run
    self.run_action(resource, action)
  File "/usr/lib/python2.6/site-packages/resource_management/core/environment.py", line 121, in run_action
    provider_action()
  File "/usr/lib/python2.6/site-packages/resource_management/core/providers/system.py", line 87, in action_create
    raise Fail("Applying %s failed, parent directory %s doesn't exist" % (self.resource, dirname))
resource_management.core.exceptions.Fail: Applying File[' hdfs://ambari01:8020/user/solr;/solr.xml'] failed, parent directory  hdfs://ambari01:8020/user/solr; doesn't exist

**Comment by abajwa-hw** [comment]
@geniuszhe have not yet tried the solr_datadir on hdfs using the ambari service, but can you try manually creating the solr user home dir on HDFS?
`
sudo -u hdfs hdfs dfs -mkdir /user/solr
`
`
sudo -u hdfs hdfs dfs -chown solr /user/solr
`

Also here is a tutorial on how to setup datadir on HDFS when installing Solr manually:
https://community.hortonworks.com/articles/1160/index-documents-using-hdpsearch-in-hdp-23.html
